#!/usr/bin/bash

if [ ! -z "$1" ]; then
	pkgs="$1"
else
	pkgs="$(find -mindepth 1 -maxdepth 1 -type d)"
fi

for package in ${pkgs}; do
	spectool --get-files --directory ${package} ${package}/${package}.spec
	mkdir -p ${package}/rpm-artifacts
	mock -r fedora-36-x86_64 --spec ${package}/${package}.spec --sources ${package} --resultdir ${package}/rpm-artifacts
done
