#!/usr/bin/bash

for package in $(find -mindepth 1 -maxdepth 1 -type d); do

	FILE_URL=$(cat ${package}/${package}.spec | grep 'Source0:' | tr -d " \t\n\r")
	FILE_URL=${FILE_URL#*:}
	FILE_NAME=${FILE_URL##*/}

	mkdir -p ${package}/rpm-artifacts
	curl -L -o ${package}/${FILE_NAME} ${FILE_URL}
	mock -r fedora-36-x86_64 --spec ${package}/${package}.spec --sources ${package}/${FILE_NAME} --resultdir ${package}/rpm-artifacts

done
